### ISSUE TITLE
Missing arrow from arg to thesis

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#1]
```
<!--Wird nicht angezeigt:-->
<Argument 1>: Schwimmen ist gesund.
  - [These 1]: A

<!--Wird angezeigt:-->
[These 2]: B
  - <Argument 2>: Schwimmen ist gesund.
```

**Comment by christianvoigt** [comment]
This is not really a bug. It is simply how the statement selection mode "statement trees" currently works: Only statements that occur outside of an argument will be inserted into the map. If you change the statement selection mode to "titled", the statement will be inserted into the map and the relation will appear. (You can try out selection modes in the browser by clicking on the "settings" button in the map view.)

So this is probably a feature request: "statement trees" selection mode should exclude statements that are only referenced inside of argument reconstructions (in relation with premises). But it should include statements that are only referenced in relations with arguments.

**Comment by christianvoigt** [comment]
the new selection methods in 1.0.0 allow arbitrary statement selection so this can be closed.
