### ISSUE TITLE
Nested Lists in non-argdown blocks

### ISSUE THREAD

**Issue by xylomorph** [christianvoigt/argdown#10]
Nicht argdown-Blöcke sollten wohl am besten alle markdown-Sachen zulassen. Das betrifft dann vor allem verschachtelte Listen außerhalb von Argumentrekos und dgl. Ich denke hier vor allem an html/markdown-export (Was das Durcheinander angeht: Wenn es nicht geht, dann lieber Einf. von Relationen und dgl. in verschachtelten Listen verbieten, als vollständig verschachtelte Listen verbieten.)

**Comment by christianvoigt** [comment]
With "non-Argdown-blocks" you probably mean Argdown block elements that do not define a statement or argument or Argdown block elements that are not represented in an argument map. But in Argdown any line of text that is not either a heading or an argument definition is interpreted as a statement. Thus, each list item defines also a normal statement that can be represented in an argument map. Currently, only headings and comments are not represented in argument maps. But as soon as we introduce grouping by headings, this will change as well.

I think it makes sense to allow list of statements or arguments and to represent such lists in argument maps. 

What you have in mind would probably better be accomplished by writing a Markdown document with Argdown sections. For that we would need to write an Argdown plugin for a Markdown parser.

**Comment by christianvoigt** [comment]
Just looked at nested lists again. This is not going to happen for now, as it would complicate the parsing process to much. 

From my point of view it still makes more sense to further work on Markdown and Latex integration. A first step can be seen in the new documentation which uses Markdown-It plugins to parse all Argdown code fences within Markdown documents.
