### ISSUE TITLE
Extension host stops in VSCODE

### ISSUE THREAD

**Issue by TimSoethout** [christianvoigt/argdown#104]
I get this error message in the developer console when opening an argdown file in VSCode, or trying to visualize one.

```
extensionService.ts:457 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
t._onExtensionHostCrashed @ extensionService.ts:457
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
t.onDidNotificationChange @ notificationsAlerts.ts:40
extensionHost.ts:231 Extension Host
extensionHost.ts:232 dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.5/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.5/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace
```

Is this a known error? Or maybe related to other VSCode plugins?

**Comment by TimSoethout** [comment]
Maybe related to this: https://github.com/Microsoft/vscode/issues/68024

**Comment by TimSoethout** [comment]
As per mentions bug link, i downgraded to vscode 1.30 and it seems to work again.

https://code.visualstudio.com/updates/v1_30

**Comment by christianvoigt** [comment]
thank you for finding this out and reporting it here, I was not aware of it. I have subscribed to the issue and will follow the discussion.

**Comment by ggbetz** [comment]
I can confirm Tim's report. The problem started to occur with one of the last updates of VS code.

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/ggbetz/.vscode/extensions/christianvoigt.argdown-vscode-1.0.5/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/ggbetz/.vscode/extensions/christianvoigt.argdown-vscode-1.0.5/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

```

**Comment by Myself5** [comment]
The same issue has been observed and fixed here: https://github.com/ritwickdey/vscode-live-server/issues/250

Looks like it's caused by the Electron and NodeJS updates in 1.31 (and above), which is why downgrading to 1.30.2 fixes the issue.

Judging by https://github.com/ritwickdey/vscode-live-server/pull/267, https://github.com/ritwickdey/vscode-live-server/commit/ca594e49635f2ef6f921ff4dd99df1a275bb3d7d seems to fix this issue.

**Comment by christianvoigt** [comment]
Thanks for the help! So it seems updating Chokidar/fsevents will fix this. I had planned to work on Argdown this week anyway so you won't have to wait long for the next release.

**Comment by hevisko** [comment]
Same issue with Version 1.32.3 (1.32.3)

**Comment by christianvoigt** [comment]
Hi, thanks for the notification, I have just tested this myself. I *did* update chokidar in the last release (which depends on fsevents), but apparently at the time chokidar had not updated fsevents and was still using 1.2.7. There were a lot of changes in the last release, so I forgot to test this again. Sorry for that.

Since then chokidar has finally updated fsevents to the new napi version so I will update it and release a patch.

**Comment by christianvoigt** [comment]
@hevisko can you please go to your `~/vscode/extensions` folder and check if there are two versions of argdown-vscode? In my deleting the older version fixed the issue.

VScode told me that it had updated the extension, but the error message was still coming from the old version. So I guess there was something wrong with the update process.
