### ISSUE TITLE
Upper-level lists: syntax-difference to markdown

### ISSUE THREAD

**Issue by xylomorph** [christianvoigt/argdown#11]
Unverschachtelte Listen:  Im Moment müssen Listen auf der obersten Ebene eingerückt sein. In Markdown geht natürlich auch:

```
1. erster Listenpunkt
2. zweiter Listenpunkt
```

ohne Einrückung.

**Comment by christianvoigt** [comment]
Right. I have to check if it is possible to change the parser accordingly without this leading to any conflicts.

**Comment by christianvoigt** [comment]
Just checked this again in the sandbox and it does seem to work now. So I probably fixed this along the way and forgot about it. :)
