### ISSUE TITLE
Why the hel (not a typo) is this written in js and using node?! 

### ISSUE THREAD

**Issue by Lovewyrm** [christianvoigt/argdown#110]
The original poster asked why we implemented our Argdown parser in Javascript and Node instead of C++.

(I have edited this message to avoid becoming distracted from this question by the abusive manner in which it was raised. Christian Voigt)

**Comment by Lovewyrm** [comment]
P.S.: Already halfway through implementing the syntax at a casual pace, using boost spirit and even with that framework the library that parses the input files is hovering around 250kb.
Actually, it's 104kb right now, but I doubt it will ever become larger than a megabyte, or two, and that's already bloat territory just for a library.
The output generators are their own binaries.

Node JS, man...Node JS for this...

**Comment by christianvoigt** [comment]
Hi Lovewyrm,

Great that you are developing an alternative parser in C++, this was actually something we were hoping for when we defined a Markdown-like syntax. 
Different people have different requirements and preferences. We do not expect our implementation to be everone's cup of tea or the best possible version of an Argdown parser.

If you are still interested, here are our reasons for choosing Typescript:

- we need the parser to run in the browser 
- we wanted to develop a VS Code extension that does not have any additional installation requirements.

I do not think that any further discussion about if language x is better than y serves any constructive purpose. 
However, if you want to keep us up to date about your own implementation of an Argdown parser, we definitely 
are very interested in that. Especially users who prefer to use the cli might switch to a leaner and faster version.

PS.: I am sorry for your disappointment and can appreciate your stylistic creativity, 
but I will not tolerate any further abusive language here and have extracted your original question from the abusive language it was embedded in.
