### ISSUE TITLE
Add support for implicit relation direction of undercut (_ instead of <_)

### ISSUE THREAD

**Issue by christianvoigt** [christianvoigt/argdown#112]
see #96.

Documentation says that it is possible, but the parser currently does not support it.

**Comment by christianvoigt** [comment]
The problem with this syntax is the ambiguity between an undercut with an implicit relation direction and the beginning of an italic range:

```Argdown
Some text
   _ This is an undercut with an implicit relation direction
   _This is an italic text range_
```

The best solution I see right now is to check if the underscore is followed by an empty space. The downside is that all other relations do not have to be followed by an empty space. Here is how the parser will behave in the next version:

```
Some text
   _This is **invalid**.
   _ This is valid.
   <_This is valid.
   _>This is valid.
   +This is valid.
   -This is valid.
```

**Comment by bd82** [comment]
Example of making a Chevrotain Parser Whitespace sensitive in a specific point
without handling Whitespace everywhere in the grammar.
- https://github.com/SAP/chevrotain/blob/master/examples/grammars/css/css.js#L431-L437

**Comment by christianvoigt** [comment]
Hi @bd82, actually the problem in this is case was not detecting the whitespace (I do that directly in the lexer with a simple Regex lookahead), but that the syntax for the undercut relation has to deviate from the syntax of the other relations by requiring an empty space. So it is not so much a technical problem, but rather a conceptual/aesthetic flaw.

Maybe the cleaner solution would be to always require an empty space after a relation symbol, but in general I try to make the Argdown parser as laissez faire as possible, similar to Markdown parsers.

Thanks again for looking into these issues and sorry for the late answer.
