### ISSUE TITLE
link to first example broken

### ISSUE THREAD

**Issue by christianvoigt** [christianvoigt/argdown#115]
>In case it's useful I immediately got a dead link https://argdown.org/guide/a-first-example/ from this page https://argdown.org/guide/
>--[pithymaxim](https://news.ycombinator.com/reply?id=20476015&goto=item%3Fid%3D20475865%2320476015)

>FYI to the owner of Argdown.org if around- Your getting started page linked here 404's: https://argdown.org/guide/a-first-example
>-- [pmarreck](https://news.ycombinator.com/reply?id=20481733&goto=item%3Fid%3D20475865%2320481733)

**Comment by pmarreck** [comment]
I think it just literally needs a `.html` added to the linked-to URL... This URL works: https://argdown.org/guide/a-first-example.html
