### ISSUE TITLE
Windows line feed (\r) in argdown cli prevents it from running on linux

### ISSUE THREAD

**Issue by oliver-frost** [christianvoigt/argdown#121]
After installing argdown with the usual

`npm install -g  @argdown/cli`

running argdown responds with

`/usr/bin/env: »node\r“: No such file or directory`

It seems like the error is due to the windows line endings. Any idea why that is?

I am running with:
`uname -a` ->
Linux laptop 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`node --version` ->
v8.10.0

**Comment by christianvoigt** [comment]
Can you post the exact Argdown command that you are running in the commandline? Try using it with the verbose flag `-v` to get more output. Or have you written your own script that could be causing this problem?

I recently switched to Windows so I can not try it out myself. In general, the code files should not contain any Windows line endings, but maybe that is not true anymore. I will have to run the tests on another computer to check it.

**Comment by oliver-frost** [comment]
I just run
`$ argdown`

Since I am on a German locale it answers with
`/usr/bin/env: »node\r“: Datei oder Verzeichnis nicht gefunden`

On an English locale it should just read
`/usr/bin/env: ‘node\r’: No such file or directory`

The argdown executable script (in my case it is located in /usr/local/bin/argdown) does not seem to get past the shebang for finding the actual node executable. It seems to be confused about the '\r' - Carriage Return preceding the newline, which is typically introduced by editing on Windows.

**Comment by christianvoigt** [comment]
Thanks for reporting this. I have checked the code base and some CLRF line endings sneaked in, even though my VS Code settings are set to LF. Maybe I have to change my git configuration. I will create a new release as fast as possible. In the meantime, please use the VS Code extension which should work.

**Comment by christianvoigt** [comment]
We did a test on a Mac today. The cli was running without problems. The issue seems to be only occurring on Linux systems.

**Comment by christianvoigt** [comment]
Ok, we tested this on an Ubuntu system today and could not reproduce the error. We used npx to test this without installing Argdown permanently, but this should not matter. This is what we did:

```bash
sudo npx -p @argdown/cli argdown map ./some-argdown-file.argdown
```

@oliver-frost Could you try this on your system to check if you can reproduce the error with this command as well?

**Comment by christianvoigt** [comment]
By the way, we tested this with node v10.6.0 so that might explain why the error did not occur. Since your version is v8.10.0 you could try to update node to fix this.

**Comment by oliver-frost** [comment]
Thanks Christian for looking into this. I am little busy at the moment, but will definitely try your suggestions soonish and report whether they succeed.

**Comment by oliver-frost** [comment]
@christianvoigt , I am back on it.

I upgraded nodejs to the current LTS release

> $ node --version
> v10.16.3

Running your suggested command

> $ sudo npx -p @argdown/cli argdown map ./some-argdown-file.argdown

results in the following error message:

>internal/modules/cjs/loader.js:638
>   throw err;
>   ^
>
>Error: Cannot find module '/home/oliver-frost/.npm/_npx/16464/lib/node_modules/@argdown/cli/node_modules/core-js/scripts/postinstall'
>    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>    at startup (internal/bootstrap/node.js:283:19)
>    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

where I do not know what is the issue.

Uninstall argdown and installing argdown with

> $ sudo npm uninstall -g  @argdown/cli
> $ sudo npm install -g  @argdown/cli

went through just fine, but still terminates

> $ argdown
> /usr/bin/env: ‘node\r’: No such file or directory

as before.

**Comment by christianvoigt** [comment]
Thanks for trying! I will remove all CRLF line endings from the code, let's hope that this solves the problem. It would be very helpful if you could try this again after the next release and report the results here as I currently have no way to reproduce this.

**Comment by christianvoigt** [comment]
Hi @oliver-frost, I finally found the time to release the next version of the cli (1.2.0). Could you please update and try it out? I removed all Windows linebreaks from the code base and ensured that this will not happen again. I hope that this finally fixes your problem.

**Comment by oliver-frost** [comment]
Hi @christianvoigt, just tried it again. Still no success...
It seems to me as if there is something off with my Linux distribution. I recently tried it on a freshly installed Ubuntu and argdown work fine. So I am not to sure what to make of it.

**Comment by christianvoigt** [comment]
Thanks for giving it another try. I also tested it again on an Ubuntu server and it worked just fine. Not sure if I should keep this open as I can not reproduce it and I am pretty sure that I have removed all Windows line endings. So I guess at the moment there is not much that I can do to help.
