### ISSUE TITLE
graphml export: custom line-width 

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#123]
In graphml-export, hard line-breaks are inserted to create multi-line nodes.

With current default-settings, there are 10-20 chars per line in exported graphml files, e.g.:

![grafik](https://user-images.githubusercontent.com/3662782/65031035-d10dfd00-d940-11e9-8938-a9ec803ccce4.png)

Maybe this can be customized? It would be nice to have (optionally) wider nodes / more text per line.

Possibly one easy way to do so is to reduce fontsize (currently 13) in `GraphMLExportPlugin.ts`.

**Comment by christianvoigt** [comment]
This should already work, please read the following sections in the guide:

- [Changing the font style of node labels](https://argdown.org/guide/changing-the-node-style.html#changing-the-font-style-of-node-labels)
- [Changing the node size in GraphML](https://argdown.org/guide/changing-the-node-size.html#changing-the-node-size-for-dot-vizjs-dagre)

Here are the current configuration options for graphml (copied from https://argdown.org/guide/configuration-cheatsheet.html):

```typescript
graphml?:{
    group?:{
      horizontalPadding?:number;
      verticalPadding?:number;
      width?: number; // used if measureLineWidth is true
      /**
       * Font to use
       *
       * Only a limited number of fonts are
       * supported,
       * see string-pixel-width documentation.
       *
       * For other fonts the width measurement will
       * fail,
       * so label text lines will not fit into nodes.
       *
       * string-pixel-width: https://github.com/adambisek/string-pixel-width
       **/
      font?:string;
      fontSize?:number;
      bold?:boolean;
    };
    argument?:{
      horizontalPadding?:number;
      verticalPadding?:number;
      width?:number;
      title?:{
        font?:string;
        fontSize?:number;
        bold?:boolean;
      };
      text?:{
        font?:string;
        fontSize?:number;
        bold?:boolean;
      };
    };
    statement?:{
      horizontalPadding?:number;
      verticalPadding?:number;
      width?:number;
      title?:{
        font?:string;
        fontSize?:number;
        bold?:boolean;
      };
      text?:{
        font?:string;
        fontSize?:number;
        bold?:boolean;
      };
    };
  };
```

**Comment by ggbetz** [comment]
Thanks, I missed that!
```
===
graphml:
    statement:
        width: 200
    argument:
        width: 200
===
```
... works perfect.
