### ISSUE TITLE
Some method to represent proof trees

### ISSUE THREAD

**Issue by Callustian** [christianvoigt/argdown#127]
Hello, is it possible to add some method to represent proof trees as tables to argdown as, for example (using a stack representation):
`` ((a c)/f (h i)/l)/k``
``a``
``c``
``----``
``f``
``++++``
``h``
``i``
``---``
``l``
``++++``
``----``
``k``
Thanks

**Comment by ggbetz** [comment]
Hi Callustian,

Thanks for the suggestion! The Argdown Syntax is supposed to represent argument maps; representing proof trees (or some other logical calculus) seems to be therefore somewhat beyond its scope. 

However, you might consider inserting tree representations in comment-sections in argdown documents, e.g.

```argdown
<!--
  (1) (2)
   ┗━┳━┛
    (3) (4)
     ┗━┳━┛
      (5)
-->
```

I've been trying this to visualize internal argument structure:

```argdown
(1) Premise       //       1  
(2) Premise       //   2   ┃        
(3) Premise       //   ┃ 3 ┃   
----              //   ┗┳┛ ┃    
(4) Conclusion    //    4  ┃   
----              //    ┗┳━┛   
(5) Conclusion    //     5    
```

Another option is to embed argdown-code-blocks in markdown documents and to use markdown to layout the tables and insert diagrams you need.

**Comment by Callustian** [comment]
Hi @ggbetz .

Thank you for your post.

If you think that proof trees are not in scope, may I propose that the argdown displays the premises indices of a conclusion to the right of the argument?

So for 

(1) First premise (this is is a normal statement 
    and you can do everything with it, we have done 
    with the statements above).
(2) [Statement 2]: We have already defined a statement 
    with this title.
    Argdown allows you to add multiple statements 
    to the same "equivalence class" by giving them 
    the same title. The statements will then be treated 
    as logically equivalent.
--
Some inference rule (Some additional info: 1,2)
--
(3) And now the conclusion 
  -> Outgoing relations of the conclusion, 
  are also interpreted as outgoing relations of 
  the whole argument.
  +> <Yet another argument>

Could you render (3) as

``(3) And now the conclusion    || 1,2 ``

or something similar? If we could use parameters instead of numbers it would be great, we could change the argument avoiding renumbering.

Please note this notation solves the problem of representing the tree or a tableau.

Thanks!

**Comment by christianvoigt** [comment]
Hi @Callustian,

are you aware that you can add arbitrary YAML metadata to statements, arguments, headings and inferences? Just put the metadata in curly brackets `{data: ['an', 'array', 'of', 'strings']}`

So you could do something like this:

```
(1) [s1]: some statement
(2) [s2]: another statement
-----
(3) The conclusion {dependsOn: ['s1', 's2']}
```

We prefer to attach this metadata to the inference like so:

```
(1) [s1]: some statement
(2) [s2]: another statement
--
{dependsOn: ['s1', 's2']}
--
(3) The conclusion
```

Take a look at the syntax docs: https://argdown.org/syntax/#statement-yaml-data

You can then for example use the JSON output to process this metadata further in your own code or even write your own small Argdown plugin to add functionality based on your metadata.

**Comment by Callustian** [comment]
Hi @christianvoigt,
thank you for your post.

At the moment I don't have much of my own time to contribute to other projects. This one seems relevant to the research programme I am doing, though. G-d willing, I shall contribute to this feature when you implement the LaTeX exporter.

Thank you!

**Comment by christianvoigt** [comment]
Cool! By the way: If you are interested in the formal side of things, look out for the next version. I am adding shortcodes for logical symbols and a special Argdown font with ligatures for them. So formalizations will be easy to add and will look great in Argdown!
