### ISSUE TITLE
A note to Christian

### ISSUE THREAD

**Issue by luddilo** [christianvoigt/argdown#149]
[Please excuse this mild issue-pollution] Great project. I would love to get in contact with you @christianvoigt , I sent you an email on the @kit.edu email that I found, not sure you got it? Best, Ludvig / ludvig[at]narratory.io

**Comment by christianvoigt** [comment]
Hi Ludvig, I am in the middle of preparing a new Argdown release and it is taking longer than expected. I was planning on answering your email afterwards, sorry for the delay.
