### ISSUE TITLE
Web-component export: Clicking to zoom in Firefox makes graph disappear

### ISSUE THREAD

**Issue by antonostrovsky** [christianvoigt/argdown#155]
First of all, thank you for making the web-component export so effortless and easy!
The VS Code plugin has updated automatically and the sought-after "web component" export link has miraculously appeared.

I have exported the attached argdown map, and I can't zoom into the resulting graph in latest Firefox:
when I click to Zoom, the graph disappears and then re-appears in the default mode.
[2. Dualism vs. Physicalism.zip](https://github.com/christianvoigt/argdown/files/4583271/2.Dualism.vs.Physicalism.zip)

TypeError: fa is undefined

**Comment by antonostrovsky** [comment]
And the *.ad file [2. Dualism vs. Physicalism (map).zip](https://github.com/christianvoigt/argdown/files/4583276/2.Dualism.vs.Physicalism.map.zip)

**Comment by christianvoigt** [comment]
Thanks for the report, that is really helpful.
I can also reproduce the bug in Firefox if I open https://argdown.org
In Chrome everything is fine, so I have to check why Firefox does not behave (should have checked it earlier).

**Comment by christianvoigt** [comment]
ok, I fixed it and updated the docs (you can test it if you want), now I just need to release all those packages again that depend on @argdown/web-components.  I will do that tomorrow.

**Comment by christianvoigt** [comment]
@argdown/web-components, argdown-vscode and @argdown/cli v1.4.8 are released now. @antonostrovsky: if the problems do not disappear, please make sure to empty your browser cache.

**Comment by antonostrovsky** [comment]
@christianvoigt Thank you for mentioning to empty the browser cache! The issue has gone away now. I will continue exporting the maps and will try integrating them with static site generators.

Thanks again for this great project!
