### ISSUE TITLE
Problem using @argdown/markdown-it-plugin (In eleventy)

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#157]
Hi, when using the markdown-it-plugin with eleventy I get the following error message (once building the site):

```
`EleventyConfigError` was thrown
> Cannot find module '../dist/render_sync).js'
Require stack:
- /Users/ggbetz/node_modules/@aduh95/viz.js/sync/index.js
- /Users/ggbetz/node_modules/@argdown/core/dist/plugins/SyncDotToSvgExportPlugin.js
- /Users/ggbetz/node_modules/@argdown/core/dist/argdown.js
- /Users/ggbetz/node_modules/@argdown/markdown-it-plugin/dist/argdown-markdown-it-plugin.js
```

That is maybe related to the following warning I previously received when installing argdown-cli:

```
npm WARN notsup Unsupported engine for @aduh95/viz.js@3.0.0-beta.9: wanted: {"node":"^12.17.0 || >=13.2.0"} (current: {"node":"12.16.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: @aduh95/viz.js@3.0.0-beta.9
```

Having installed the latest version of node the error vanished.

The statement "You need at least Node 8.0.0" at https://argdown.org/guide/installing-the-commandline-tool.html#features-of-the-commandline-tool needs to be updated. :-)

**Comment by christianvoigt** [comment]
The installation warning can be ignored as we are currently not using @aduh95/viz.js with new node features.

The error is caused by a typo in @aduh95/viz.js, I will open an issue there.
