### ISSUE TITLE
argdown-map instead of argdown in markdown-it

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#158]
Hi! When using

```
const argdownConfig = { webComponent: { withoutHeader: true }}
```

as configuration for the `@argdown/markdown-it-plugin`, an `argdown` codeblock is rendered as argument-map, not as argdown code.

**Comment by christianvoigt** [comment]
For now you can try the following workaround that might work:

```javascript

const argdownConfig = { webComponent: { withoutHeader: true, initialView: "source" }}
```

**Comment by christianvoigt** [comment]
I could not reproduce your issue. Could you please post the Argdown source code and the complete configuration of markdown-it that was causing it? Maybe something else is behind this.
