### ISSUE TITLE
Running Argdown on CI

### ISSUE THREAD

**Issue by kvark** [christianvoigt/argdown#167]
I want to run it in Github Actions in order to check the arguments for correctness. So I don't need to generate anything, I basically need the parser only, something like
```
argdown parse
```
More importantly, I want it to return a non-zero error code on detecting errors (or warnings, should be configurable).
Currently, if I run `argdown html`, for example, and it detects an error, it still tries to proceed and generate the artifacts, make it really challenging to find out it if succeeds even.

**Comment by christianvoigt** [comment]
Hi, great use case! I definitely would like to support it. You have basically two options right now:

- Use `@argdown/cli` with a config file and define a custom process
- Write your own node script that uses the argdown instance from the `@argdown/node` package (which is also used internally by `@argdown/cli`)

As it is easier, let's first try the first option. Here are the relevant sections in the docs:

- This section describes [how to run custom processes](https://argdown.org/guide/running-custom-processes.html) with `@argdown/cli`
- Here is how to define a [custom process](https://argdown.org/guide/loading-custom-plugins-in-a-config-file.html)

I think your process would simply look like this: 

```js
module.exports{
    processes: {
        "parse": {
            // We could add additional configuration settings here.
            // But currently we only want to define our process here:
            process: [
            "load-file", // loads Argdown files (request.input)
            "parse-input", // parses them (response.ast)
            ]
        }
    }
}
```

Also relevant for you might be the global `throwExceptions` setting and the `throwExceptions` setting of the parser plugin. Take a look [here](https://argdown.org/guide/configuration-cheatsheet.html) for those.

If you run into any problems or have more questions, just let me know. Also even if you are successful it might be interesting for other users how you got it working.

**Comment by kvark** [comment]
Thank you for responding in such a great detail!

I tried to add a custom process like you suggested. First, it's totally unclear how that looks like in JSON configuration. Second, just copying verbatim the config you posted doesn't appear to be reporting any errors: `argdown run parse` just runs and exists, even if there are errors reported by, say `argdown html`. What's more confusing is that VSCode complains about the JS syntax being wrong (error "ts(1005)" - expected ";") in a few places... I'm far from JS development, so it's all foreign ground to me, and I haven't gotten it working.

> Also relevant for you might be the global throwExceptions setting and the throwExceptions setting of the parser plugin.

I did try that earlier, and while it prints out the exception, it doesn't change the exit status code. See [actions run](https://github.com/kvark/webgpu-debate/runs/819034666?check_suite_focus=true#step:5:6).

What I figured out yesterday was redirecting the error output into a file and checking it for being empty. See the [configuration](https://github.com/kvark/webgpu-debate/blob/b28252ea99aef8989858ece09f74dc0758e3d46c/.github/workflows/CI.yml#L13). It works, but I'm open to making it better :)

Overall, I'm very satisfied with Argdown, and I use it in https://github.com/kvark/webgpu-debate . There is a github action for  CI checks on PR, and an action to build the web component and upload it to github-pages automatically. I believe it could be a good example for other projects to follow. I also wrote down a blog post about this in http://kvark.github.io/tech/arguments/2020/06/30/technical-discussions.html

**Comment by christianvoigt** [comment]
Oh yes, I see, there is a bug in the commands. Currently in `@argdown/cli` the exceptions are logged instead of being thrown (for example see [here](https://github.com/christianvoigt/argdown/blob/9e7342b2f94daaad62d943a68e73114feea291b1/packages/argdown-cli/src/commands/RunCommand.ts#L19)). If `throwExceptions` is set, this should not happen (and I should probably also add a flag for `@argdown/cli`.

I plan to do some bug fixing in the coming weeks and will also fix this. I can also add a `parse` command to `@argdown/cli` to make this even easier. Until then, you probably have to live with your workaround.

Just for completeness sake, here is how your json config file should look:

```json
{
    "parser": {
        "throwExceptions": true
    },
    "processes": {
        "test": { "process": ["load-file", "parse-input"] }
    },
    "throwExceptions": true,
    "logExceptions": false
}
```
And here is the [config js file](https://github.com/christianvoigt/argdown/blob/master/packages/argdown-cli/test/add-plugin.argdown.config.js) that is used for testing custom plugin support.

Thanks for the links and the blog post, it's great to see Argdown used outside of philosophy seminars!

**Comment by christianvoigt** [comment]
Hi @kvark, I finally finished the work on v1.5.0. You can now simply run `argdown [input file glob]` and it will return with an error code if the parser returns any syntax errors. I you are only interested in the error code, you can now use the `--silent` option to suppress any feedback messages.

I also added "Intellisense" support for Argdown config files in VSCode via a JSON schema. That should make it much easier to find your way through the syntax and to explore the available configuration options.
