### ISSUE TITLE
Layout der Thesen

### ISSUE THREAD

**Issue by lilysabath** [christianvoigt/argdown#17]
Im Moment sind die Thesen in der Map nur durch eine andere Farbe von den Argumenten unterschieden.
Ich finde, dass es hilfreich sein könnte, wenn die Thesen visuell mehr hervorstehen würden.

**Comment by lilysabath** [comment]
Dabei wäre es vielleicht hilfreich, die Thesen nach oben zu stellen.
Dies könnte auch zum Verständnis beitragen, da man automatisch von oben nach unten liest.
Bsp: 
![bildschirmfoto 2017-04-25 um 15 52 58](https://cloud.githubusercontent.com/assets/27997967/25388885/4cb227f2-29cf-11e7-808a-49869886a5b9.png)
Hier fände ich es praktischer, wenn die These oben steht, darunter das Argument "Untitled 1", gefolgt von "Untitled 2", da dies die Reihenfolge ist, in der man die Karte lesen muss.

**Comment by christianvoigt** [comment]
This is a graph layout feature request. Argdown currently does not do any graph layouting. The graph layout in the browser editor is done by viz.js, not by Argdown. It is possible to use the dot export (and later the graphml export) together with different tools for graph layouting (i.e. yEd or Graphviz) to achieve the desired results.
