### ISSUE TITLE
command 'argdown.showPreviewToSide' not found

### ISSUE THREAD

**Issue by Keys42** [christianvoigt/argdown#190]
Just installed extension to vs code. 

When I preview the map it works. However, when I close it again, I receive the error "command 'argdown.showPreviewToSide' not found". I cannot get the preview to work again

**Comment by christianvoigt** [comment]
Thanks for your report. I could not reproduce it with Windows 10 VSCode v1.49 and Argdown v1.5.0. What OS and which versions of VSCode and the Argdown extension are you using? How do you open the preview?

**Comment by Keys42** [comment]
Mac OS. VS Code 1.49.1 and Argdown V 1.5.0

**Comment by christianvoigt** [comment]
We could not reproduce the issue on a Mac either. But we do not have a "run code" button in VSCode. In my version I have the following options to open the preview:

- if the Argdown document is open I have a preview button on the right of the tab bar "Open Preview to the Side" (do you mean that one?)
- I can right click on the tab and click on "Open Preview"
- I can open the File Explorer and right click on an Argdown file. In the context menu there is an "Open Preview" option

Neither one of those is causing an issue in our versions. 

Have you tried to uninstall/reinstall the extension? To make sure that you download the extension again, you have to delete it from your `~/.vscode/extensions` folder.

**Comment by christianvoigt** [comment]
Closing this, because it was not reproducible and the issue was inactive since September. I will reopen it if anyone still experiences this problem.
