### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by lilysabath** [christianvoigt/argdown#20]
Would it be possible to get a message when an error has been made?
As of now, it's sometimes difficult to see where I made a mistake, and the map won't work, seemingly for no reason.

**Comment by christianvoigt** [comment]
Yes, we definitely need a linter package for Atom.

**Comment by christianvoigt** [comment]
This has now been implemented. argdown-parser 0.5.0 includes the new ArgdownErrorMessageProvider. There is still much room for improvement regarding the error messages. Proposals for better error reports should be added as new issues.
