### ISSUE TITLE
update Chevrotain package

### ISSUE THREAD

**Issue by amdecker** [christianvoigt/argdown#223]
I've decided to start from scratch again on the Obsidian plugin. I get an error when running `npm run dev`

It looks like updating chevrotain in @argdown/core will fix it
See https://github.com/Chevrotain/chevrotain/issues/1441

```
Error: Could not load C:\Users\adder\Documents\obsidian-notes\.obsidian\plugins\obsidian-argdown-plugin2\node_modules\@argdown\core\node_modules\chevrotain\lib_esm\api_esm.mjs (imported b
y node_modules\@argdown\core\dist-esm\index.js): ENOENT: no such file or directory, open 'C:\Users\adder\Documents\obsidian-notes\.obsidian\plugins\obsidian-argdown-plugin2\node_modules\@
argdown\core\node_modules\chevrotain\lib_esm\api_esm.mjs'
```

**Comment by christianvoigt** [comment]
Hi, I updated the dependency and released @argdown/core@v1.7.1 and @argdown/node@v1.7.1

Let me know if you come across any other issues.
