### ISSUE TITLE
Problems in rendering arg nodes in Veggie Debate

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#24]
There are several issues when rendering the veggie debate, as the attached PDF shows.

[veggie_debate.pdf](https://github.com/christianvoigt/argdown/files/974396/veggie_debate.pdf)

The original argdown-file:

[veggie_debate.argdown.txt](https://github.com/christianvoigt/argdown/files/974399/veggie_debate.argdown.txt)

**Comment by christianvoigt** [comment]
Can you be more specific? To enable us to better keep track of bug fixes, each bug should be opened as a separate issue.

**Comment by ggbetz** [comment]
Fair point! I'll re-open two more specific issues!
