### ISSUE TITLE
dot layout configuration

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#27]
I had to add some additional parameters to the dot file in order to generate a reasonable layout, i.e.

```
concentrate=true;
ratio="fill";
size="10,10";
```

It would be cool if such additional settings could be stored in a configuration that is used by the argdown programm.

**Comment by christianvoigt** [comment]
Do you think these are good default settings, or were they specific to your map?

Are there any other DOT settings that could be useful for tweaking the layout?

**Comment by ggbetz** [comment]
These setting were highly specific and make only sense for the particular case at hand. I don't see any settings that make generally more sense than the default setting.

**Comment by christianvoigt** [comment]
resolved in https://github.com/christianvoigt/argdown-map-maker/commit/02e111eb0e6c2dbf431bce04983a8eccfef8d1c2

**Comment by TimSoethout** [comment]
Small question: Is it possible to use this feature from a `.argdown` file?

I have this on top of the file and use the Viz.js renderer, but it seems to have no impact:
```
===
model:
//    removeTagsFromText: true
selection:
  excludeDisconnected: false
map:
  graphVizSettings: 
    rankDir: 'RL'
        
===
```

**Comment by christianvoigt** [comment]
Hi,
you have to change two things: 

* graphVizSettings is a config option of the DotExportPlugin, so change `map` to `dot`
* use `rankdir` instead of `rankDir`

```argdown
===
model:
//    removeTagsFromText: true
selection:
  excludeDisconnected: false
dot:
  graphVizSettings: 
    rankdir: RL
       
===
```

For all config options, take a look at the [cheat sheet](https://argdown.org/guide/configuration-cheatsheet.html).

**Comment by TimSoethout** [comment]
Cheers, was looking through the documentation, but with the wrong keyword (layout).
