### ISSUE TITLE
argdown-vscode: punctuation breaks syntax highlighting

### ISSUE THREAD

**Issue by masonlr** [christianvoigt/argdown#285]
I'm wanting to write sentences that have mentions in them. If you add punctuation after a mention then the highlighting breaks. For a reproducible example, take https://argdown.org/syntax/#pcs-statements from the docs and write in VS Code as:

```argdown
[Intelligent Design]: The world seems
intelligently designed.

[God]: God exists.

<Teleological proof>

(1) [Intelligent Design]
(2) [Best Explanation]: The best
    explanation for why the world seems
    intelligently designed
    (cf. @[Intelligent Design]),
    is that _there is_ an
    intelligent being designing it.
-----
(3) **Some** intelligent being
    designing the world exists.
    {sources: [
        "Cleanthes"
    ]}
(4) The only intelligent being
    that could [design the world](https://en.wikipedia.org/wiki/Intelligent_design)
    is God. #deism
-----
(5) [God]
```

The mention `@[Intelligent Design]` isn't highlighted:

![image](https://user-images.githubusercontent.com/5828176/129665967-36078206-1da5-473f-a137-4f4c0aecc67e.png)

If you put a space after it, then we get highlighting:

![image](https://user-images.githubusercontent.com/5828176/129666068-49e6ecbe-6c05-40e0-b4c0-fb244706eec9.png)

**Comment by christianvoigt** [comment]
Fixed in the latest version of argdown-vscode.

**Comment by masonlr** [comment]
@christianvoigt, thanks!
