### ISSUE TITLE
Argument Map Themes

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#30]
It were be cool if the style of an argument map, e.g.

- arrow color and width
- font family and size
- node color and shape 
- etc.

would be stored in a separate (css) file. Each such file would then define an argument mapping theme and users could share their themes.

**Comment by christianvoigt** [comment]
Relevant changes in 0.1.0: 

  - the new Dagre View uses css for styling the graph
  - argdown.config.js has some options for configuring the dot export (and thus the Graphviz view), like tag and group colors.

In the future it makes sense to add more configuration options for the dot export like font family and size to the config, but for now I am closing this issue.
