### ISSUE TITLE
Content with square brackets cannot be parsed

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#38]
For example
```argdown
[T]: Thesis
  + I don't believe [...] this!
```
throws a `MismatchedTokenException`.

**Comment by xylomorph** [comment]
Also stumbled over that one. I guess we need e.g. a backslash escape ("\[ ") for argdown syntax indicators.

**Comment by christianvoigt** [comment]
yes that's right. I will add backslash escaping for single characters in the next release as this is an easy fix.

**Comment by christianvoigt** [comment]
the parser now recognizes backslash escaping in Argdown code except for occurrences in statement titles, argument titles and links (for special technical reasons).

In the model text is stored in their unescaped versions. Export plugins are expected to escape characters as needed (I already added this to the HtmlExport).
