### ISSUE TITLE
Feature request: Collaborative Multiuser WebUI for editing (like a Google Docs or Etherpad)

### ISSUE THREAD

**Issue by aindilis** [christianvoigt/argdown#428]
Hi,

First off, I love Argdown, though I'm still confused about a few parts. Thanks for making it!

We would love to see Argdown be able to be (edited and visualizations rendered) collaboratively.

Is there such a feature, or is it planned to be added?

Thanks,
Andrew

**Comment by ggbetz** [comment]
Hi Andrew! 

Let me share the set-up we've been using for similar purposes. A couple of years ago, we were doing a live-reconstruction (real-time argument-mapping with projection of evolving argument map) of a public discussion event. There were three argument analysts. We were using VS Code on all Laptops, had the [Argdown Extension](https://argdown.org/guide/installing-the-vscode-extension.html) installed, and made use of [Live Share](https://code.visualstudio.com/learn/collaboration/live-share), which allowed us to edit (with three cursors), one and the same argdown file simultaneously. We've used an additional computer, connected via LiveShare to the same document, to project the Argument Map Preview via VS Code. That worked well. Do you think that might be an option for you? 

Best,
Gregor

**Comment by aindilis** [comment]
Hi Gregor!

I think this looks like it will work, and I appreciate your response!

Cheers,
Andrew
