### ISSUE TITLE
Installing argdown-cli 0.9.0 fails under Linux because of sharp.node module

### ISSUE THREAD

**Issue by christianvoigt** [christianvoigt/argdown#47]
Installation of the sharp module for linux (needed for png export) seems to fail. @xylomorph: Can you verify this?

Eugen, can you remove argdown and reinstall it completely? (`npm remove argdown-cli -g` and after that `npm install argdown-cli -g`).

I switched from using PhantomJs to sharp exactly because of similar problems. So this is a disappointment. :(

Mail snippet:

<blockquote>
Die Installation von argdown schien zu funktionieren (es kamen zwar zwei Warnmeldungen, aber auch der Hinweis + argdown-cli@0.9.0 updated 2 packages in 8.364s.

Doch wenn ich argdown --version eingebe, kommt eine lange Fehlermeldung:

module.js:545
    throw err;
    ^
Error: Cannot find module '../build/Release/sharp.node'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/argdown-cli/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
</blockquote>

**Comment by christianvoigt** [comment]
Sharp normally uses prebuilt binaries. In some cases it can not provide these binaries and tries to build a new one during installation. For this, a proper build environment is needed. See http://sharp.pixelplumbing.com/en/stable/install/#prerequisites

<blockquote>
Sharp will be built from source at install time when:

 * a globally-installed libvips is detected,
 * pre-compiled binaries do not exist for the current platform and Node version, or
 * when the npm install --build-from-source flag is used.

</blockquote>

So my guess is that Eugen is using a linux distribution for which no pre-compiled binary is provided. In such a case the installation will only succeed if the following requirements are met: 

<blockquote>
 * C++11 compatible compiler such as gcc 4.8+, clang 3.0+ or MSVC 2013+
 * node-gyp and its dependencies (includes Python)
</blockquote>

@xylomorph: Could you help Eugen with installing these requirements under Linux? 

The more general question is if these problems occur for most Linux users or if this is a special case. @xylomorph: Do you also have this problem?

If that is the case I would probably be forced to remove the png export completely from argdown-cli. It is simply not worth causing such headaches.

**Comment by xylomorph** [comment]
Yes, I will help Eugen!

What regards your question: It seems I have a prebuild version my system (Ubuntu 16.04.2 LTS). npx says

```bash
sebastian@sebastian-ThinkPad-X1-Carbon-3rd:~/tmp/can-be-deleted/argdown$  npx argdown-cli@0.9.0 -f png --density=300 --width=3000 --height=3000  ./farbentest.argdown 
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-linux-x64.tar.gz
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/sharp-v0.20.1-node-v59-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/sebastian/.npm/_prebuilds/https-github.com-lovell-sharp-releases-download-v0.20.1-sharp-v0.20.1-node-v59-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /home/sebastian/.npm/_prebuilds/https-github.com-lovell-sharp-releases-download-v0.20.1-sharp-v0.20.1-node-v59-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/sebastian/.npm/_npx/7275/lib/node_modules/argdown-cli/node_modules/sharp/build/Release/sharp.node
prebuild-install info unpack required /home/sebastian/.npm/_npx/7275/lib/node_modules/argdown-cli/node_modules/sharp/build/Release/sharp.node successfully
prebuild-install info install Successfully installed prebuilt binary!
```
Though, no idea what can be inferred about most Linux users...

**Comment by JenkaUbuntu** [comment]
Installation of argunet still fails:
* gcc was installed on my laptop when I first tried to update argdown to 0.9.0
* node-gyp I added today
* having gcc (5.4) and node-gyp installed, I tried to install argdown-cli again. The installation process failed ending in an infinite loop with warning `user root does not have the permission to access the dev dir  "/usr/local/lib/node_modules/argdown-cli/node_modules/sharp/.node-gyp"`(screenshot attached)
![screenshot from 2018-04-11 15-45-11](https://user-images.githubusercontent.com/38288475/38621484-45d53ba4-3da1-11e8-9ad7-825a03cae9f0.png)

**Comment by christianvoigt** [comment]
see https://github.com/nodejs/node-gyp/issues/454#issuecomment-315691803

Have you run `npm install argdown-cli -g` with or without sudo?
You can try using `--allow-root` or `--unsafe-perm`, so this is considered to be unsafe.  The safe way seems to be to use `nvm` (see link above).

**Comment by JenkaUbuntu** [comment]
`Have you run npm install argdown-cli -g with or without sudo?`
I had to run npm as root, for the installation process needs to change libraries in a root directory /usr
`The safe way seems to be to use nvm (see link above).`
Indeed, using nvm works.
Here are the steps:
1. install nvm: https://github.com/tbaltrushaitis/tower-strike#install-nvm
2. install nodejs (version 9.11.1): `nvm install 9.11.1`
3. install argdown: `nvm exec npm install -g argdown-cli`

**Comment by christianvoigt** [comment]
Great!

Our next problem is that argdown-cli is used in the VS Code extension. So if you install or update the extension, it will try to install sharp again (once I release a new version of the extension) and it will probably fail because it runs without nvm. 

One solution would be if the extension depended on a globally installed version of argdown-cli, but that would require everyone to install it separately, which is fixing a problem by making it worse.

So I might still have to remove the PNG export from argdown-cli.

**Comment by christianvoigt** [comment]
Installing sharp in the VS Code extension also lead to problems, so that decided the issue for me. I have removed the PNG export from argdown-cli.

If you want to use it (after all it works perfectly fine, once you have installed it), you can now add it to argdown-cli as an external plugin. Please visit the new home of the plugin for further details: https://github.com/christianvoigt/argdown-png-export

I am sorry for the inconvenience, but at least the whole process lead to a really cool new feature of argdown-cli: you can now add your own custom plugins in the config file and execute them by using `argdown run [my process name]`! @xylomorph I think you will really like this (take a look [here](https://github.com/christianvoigt/argdown/blob/master/docs/Configuration.md)) :)
