### ISSUE TITLE
Linter: error message in wrong line

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#56]
Hi, when an illegitimate blank line is added after a thesis, error message is shown in the wrong line.

![grafik](https://user-images.githubusercontent.com/3662782/40924538-c1d733ba-6817-11e8-9c2c-5527677a7132.png)

In the example, the problem occurs in line 2 (or 3), but is attributed to line 4

**Comment by christianvoigt** [comment]
this is already fixed in the latest argdown-parser version. You can verify this in argdown-cli. It will take still some time until I release the next version of the vs code extension and the browser based editor.
