### ISSUE TITLE
No Warning/Error Message about wrong syntax

### ISSUE THREAD

**Issue by cwkit** [christianvoigt/argdown#63]
To mark Headings in Argdown you have to use '# Heading'. But the more intuitive use of '#Heading' without space is ignored when generating the map, while not producing an Error Message in VS Code. An Error Message or Warning could be helpful.

**Comment by christianvoigt** [comment]
Strings like "#my-tag" at the beginning of a line are valid Argdown strings and should not cause any syntax errors. So this is not a bug, but a feature request: new blocks of text that start with a # not followed by a space character should be parsed as headings, not as a statements that start with a tag.

I do not think that this would be a real improvement. The CommonMark specs also does not allow a space after the last hash character (even if this ignored by most implementations): https://spec.commonmark.org/0.24/#atx-headings

See especially https://spec.commonmark.org/0.24/#example-29 for the reasoning behind this.
