### ISSUE TITLE
Incorrect relation

### ISSUE THREAD

**Issue by xylomorph** [christianvoigt/argdown#7]
Ich hätte gedacht, dass

```
[Diskriminierungsverbot]: Jede Art von Diskriminierung ist verboten.
   +> <A2>: Gebot der FQ wegen Diskriminierung.
   +> <A1>: FQ ist auch Diskriminierung.
      -> [Gebot der FQ]: Es ist geboten die Frauenquote (der Art F) einzuführen.
```

das gleiche ergeben sollte wie:

```
[Diskriminierungsverbot]: Jede Art von Diskriminierung ist verboten.
   +> <A1>: FQ ist auch Diskriminierung.
      -> [Gebot der FQ]: Es ist geboten die Frauenquote (der Art F) einzuführen.
   +> <A2>: Gebot der FQ wegen Diskriminierung.
```
macht es aber nicht. 

**Das Merkwürdige**: Im Browswer gibt es das Problem nicht. Hab es in Atom gemacht & als dot exportiert (und auch alle tabs in spaces umwandeln lassen).

Bild für letzteren Fall. 

![bug-01](https://cloud.githubusercontent.com/assets/10729347/24954283/fe213f60-1f7e-11e7-83d0-e6b5dfe28ab3.png)

**Comment by christianvoigt** [comment]
Can you please update argdown-cli and try again?

This is probably fixed in the current release of argdown-parser. The browser tool is already up to date, your version of argdown-cli was probably not, so this explains the difference.
