### ISSUE TITLE
dot settings in frontmatter

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#81]
I want to specify rankdir option for dot export in argdown frontmatter. How exactly can I do this? I tried
```
===
dot: {
    graphVizSettings: {
      "rankdir": "TB"  
    }
  }
===
```

and various other versions, but the argument map was not affected.

**Comment by christianvoigt** [comment]
This is only a problem of the Sandbox. You have the options to change the settings in the menu on the right. This does basically the same as an external config file does: It will overwrite any settings in the frontmatter section. So at the moment the rankdir frontmatter settings will always be overwritten by the rankdir settings in the menu.

Ideally the user should be able to use a setting in the external config file that decides which settings should have precedence.
