### ISSUE TITLE
References to so far non-defined statements

### ISSUE THREAD

**Issue by xylomorph** [christianvoigt/argdown#9]
Also das geht natürlich:

```
[p]: p
   - [notp]: notp


<A1>: Argument 1

(1) pr
----
(2) [notp]
```

Aber dann werden in der map p und notp immer angezeigt, was schnell zum Pfeilchaos führt. Es scheint ja so zu sein, dass Statements nicht in der Karte als Thesenkasten landen, wenn sie nur innerhalb von Argument def. werden und nicht außerhalb referenziert werden. Daher bräuchte ich für obigen Fall sowas ähnliches, wie

```
[p]: p


<A1>: Argument 1

(1) pr
----
(2) [!p]: notp
```

**Comment by xylomorph** [comment]
Ok, erledigt (zumindest für diesen Anwendungsfall). Wir haben ja:

```
[p]: p

<A1>: Argument 1

(1) pr
----
(2) [notp]: not p
   >< [p]
```

**Comment by christianvoigt** [comment]
Please try out the "settings" in the map view of the browser tool (click the button at the bottom).

The map export currently offers 5 different methods by which the statements are selected that will be represented as nodes in the map.

You can also use these different methods in the argdown cli by using the -m option: 

```bash
argdown dot -m [all|titled|roots|statement-trees|with-relations]
```
