### ISSUE TITLE
Language Server should not send parser errors to log

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#97]
Whenever one creates temporarily invalid argdown code while typing -- which is, e.g., inevitable when typing `<Argument>: description` because `<Argument>:` is invalid -- the console pops up. Can this behavior be switched off? Is it possible to switch it off by default?

**Comment by christianvoigt** [comment]
This seems to be an issue of VS Code 1.29.0, right? I do not think the console popped up in 1.28.0.

**Comment by ggbetz** [comment]
I installed 1.29.0 today, but I had this issue before (with 1.28.0).

**Comment by ggbetz** [comment]
The concole does not pop with any error; however, this is (invalid) code that, if eneterd, makes the console still pop up (namely when typing ":"):
```argdown
A statement
[t]: t
```
Error message reads:
```
[Error - 10:58:59 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'members' of undefined
  Code: -32603 
```
